# Generated by Django 2.0.13 on 2019-04-29 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20190428_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='creator',
            field=models.ForeignKey(help_text='컨텐츠 생성자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contents',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='컨텐츠 생성시간'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='main_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='컨텐츠 사진'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='school',
            field=models.ForeignKey(help_text='학교', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='컨텐츠 내용'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시간'),
        ),
    ]
