# Generated by Django 2.0.13 on 2019-04-24 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(blank=True, choices=[(0, '학생'), (1, '선생님')])),
                ('role', models.IntegerField(blank=True, choices=[(1, 'Manager'), (0, 'Nomal User')])),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='join',
            name='member',
        ),
        migrations.RemoveField(
            model_name='join',
            name='school',
        ),
        migrations.AddField(
            model_name='school',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.AddField(
            model_name='schoolmember',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joins', to='schools.School'),
        ),
    ]
