# Generated by Django 2.0.13 on 2019-04-29 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20190428_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member',
            field=models.ForeignKey(help_text='학교 구성원', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.IntegerField(choices=[(1, '관리자'), (0, '일반 회원')], default=0, verbose_name='학교 역할'),
        ),
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.ForeignKey(help_text='학교', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joins', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='school',
            name='creator',
            field=models.ForeignKey(help_text='학교 생성자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='학교 삭제 시간'),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='학교 사진'),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(max_length=140, null=True, verbose_name='학교 위치'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=140, verbose_name='학교 이름'),
        ),
        migrations.AlterField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='school',
            field=models.ForeignKey(help_text='학교', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribes', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='subscriber',
            field=models.ForeignKey(help_text='학교 구독자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시간'),
        ),
    ]
