# Generated by Django 2.0.13 on 2019-06-03 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0006_auto_20190516_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('main_image', models.ImageField(null=True, upload_to='', verbose_name='컨텐츠 사진')),
                ('text', models.TextField(blank=True, null=True, verbose_name='컨텐츠 내용')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='컨텐츠 생성시간')),
                ('creator', models.ForeignKey(help_text='컨텐츠 생성자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='학교', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='schools.School')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.IntegerField(default=0, verbose_name='학교 역할'),
        ),
    ]
